{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elementa.serviceAccount" . }}
  labels:
    {{- include "elementa.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
